# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.2.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.2.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Library/Caches/Homebrew/tigervnc-1.4.0

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Library/Caches/Homebrew/tigervnc-1.4.0

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.2.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.2.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.2.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.2.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.2.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.2.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Library/Caches/Homebrew/tigervnc-1.4.0/CMakeFiles /Library/Caches/Homebrew/tigervnc-1.4.0/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Library/Caches/Homebrew/tigervnc-1.4.0/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dmg

# Build rule for target.
dmg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dmg
.PHONY : dmg

# fast build rule for target.
dmg/fast:
	$(MAKE) -f CMakeFiles/dmg.dir/build.make CMakeFiles/dmg.dir/build
.PHONY : dmg/fast

#=============================================================================
# Target rules for targets named servertarball

# Build rule for target.
servertarball: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 servertarball
.PHONY : servertarball

# fast build rule for target.
servertarball/fast:
	$(MAKE) -f CMakeFiles/servertarball.dir/build.make CMakeFiles/servertarball.dir/build
.PHONY : servertarball/fast

#=============================================================================
# Target rules for targets named tarball

# Build rule for target.
tarball: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tarball
.PHONY : tarball

# fast build rule for target.
tarball/fast:
	$(MAKE) -f CMakeFiles/tarball.dir/build.make CMakeFiles/tarball.dir/build
.PHONY : tarball/fast

#=============================================================================
# Target rules for targets named udmg

# Build rule for target.
udmg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 udmg
.PHONY : udmg

# fast build rule for target.
udmg/fast:
	$(MAKE) -f CMakeFiles/udmg.dir/build.make CMakeFiles/udmg.dir/build
.PHONY : udmg/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named os

# Build rule for target.
os: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os
.PHONY : os

# fast build rule for target.
os/fast:
	$(MAKE) -f common/os/CMakeFiles/os.dir/build.make common/os/CMakeFiles/os.dir/build
.PHONY : os/fast

#=============================================================================
# Target rules for targets named rdr

# Build rule for target.
rdr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rdr
.PHONY : rdr

# fast build rule for target.
rdr/fast:
	$(MAKE) -f common/rdr/CMakeFiles/rdr.dir/build.make common/rdr/CMakeFiles/rdr.dir/build
.PHONY : rdr/fast

#=============================================================================
# Target rules for targets named network

# Build rule for target.
network: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 network
.PHONY : network

# fast build rule for target.
network/fast:
	$(MAKE) -f common/network/CMakeFiles/network.dir/build.make common/network/CMakeFiles/network.dir/build
.PHONY : network/fast

#=============================================================================
# Target rules for targets named Xregion

# Build rule for target.
Xregion: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Xregion
.PHONY : Xregion

# fast build rule for target.
Xregion/fast:
	$(MAKE) -f common/Xregion/CMakeFiles/Xregion.dir/build.make common/Xregion/CMakeFiles/Xregion.dir/build
.PHONY : Xregion/fast

#=============================================================================
# Target rules for targets named rfb

# Build rule for target.
rfb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rfb
.PHONY : rfb

# fast build rule for target.
rfb/fast:
	$(MAKE) -f common/rfb/CMakeFiles/rfb.dir/build.make common/rfb/CMakeFiles/rfb.dir/build
.PHONY : rfb/fast

#=============================================================================
# Target rules for targets named vncviewer

# Build rule for target.
vncviewer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vncviewer
.PHONY : vncviewer

# fast build rule for target.
vncviewer/fast:
	$(MAKE) -f vncviewer/CMakeFiles/vncviewer.dir/build.make vncviewer/CMakeFiles/vncviewer.dir/build
.PHONY : vncviewer/fast

#=============================================================================
# Target rules for targets named icons

# Build rule for target.
icons: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 icons
.PHONY : icons

# fast build rule for target.
icons/fast:
	$(MAKE) -f media/CMakeFiles/icons.dir/build.make media/CMakeFiles/icons.dir/build
.PHONY : icons/fast

#=============================================================================
# Target rules for targets named conv

# Build rule for target.
conv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 conv
.PHONY : conv

# fast build rule for target.
conv/fast:
	$(MAKE) -f tests/CMakeFiles/conv.dir/build.make tests/CMakeFiles/conv.dir/build
.PHONY : conv/fast

#=============================================================================
# Target rules for targets named convperf

# Build rule for target.
convperf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 convperf
.PHONY : convperf

# fast build rule for target.
convperf/fast:
	$(MAKE) -f tests/CMakeFiles/convperf.dir/build.make tests/CMakeFiles/convperf.dir/build
.PHONY : convperf/fast

#=============================================================================
# Target rules for targets named test_util

# Build rule for target.
test_util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_util
.PHONY : test_util

# fast build rule for target.
test_util/fast:
	$(MAKE) -f tests/CMakeFiles/test_util.dir/build.make tests/CMakeFiles/test_util.dir/build
.PHONY : test_util/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... udmg"
	@echo "... uninstall"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... dmg"
	@echo "... tarball"
	@echo "... list_install_components"
	@echo "... servertarball"
	@echo "... install/local"
	@echo "... os"
	@echo "... rdr"
	@echo "... network"
	@echo "... Xregion"
	@echo "... rfb"
	@echo "... vncviewer"
	@echo "... icons"
	@echo "... test_util"
	@echo "... convperf"
	@echo "... conv"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

